// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MutinyBot.Database;

namespace MutinyBot.Migrations
{
    [DbContext(typeof(MutinyBotDbContext))]
    [Migration("20210708225108_MembersGuildProperty")]
    partial class MembersGuildProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9");

            modelBuilder.Entity("MutinyBot.Models.GuildModel", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("MutinyBot.Models.MemberModel", b =>
                {
                    b.Property<ulong>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CurrentMember")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleDictionary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesJoined")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesMuted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VerifiedPetOwner")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemberId", "GuildId");

                    b.HasIndex("GuildId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MutinyBot.Models.PetModel", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PetImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PetName")
                        .HasColumnType("TEXT");

                    b.HasKey("PetId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("MutinyBot.Models.UserModel", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MutinyBot.Models.GuildModel", b =>
                {
                    b.OwnsOne("MutinyBot.Models.GuildSettingModel", "GuildSettings", b1 =>
                        {
                            b1.Property<ulong>("GuildId")
                                .HasColumnType("INTEGER");

                            b1.Property<ulong>("JoinLogChannelId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("JoinLogEnabled")
                                .HasColumnType("INTEGER");

                            b1.Property<ulong>("ModerationLogChannelId")
                                .HasColumnType("INTEGER");

                            b1.Property<ulong>("MuteRoleId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("TrackMemberRoles")
                                .HasColumnType("INTEGER");

                            b1.HasKey("GuildId");

                            b1.ToTable("GuildSettings");

                            b1.WithOwner()
                                .HasForeignKey("GuildId");
                        });

                    b.Navigation("GuildSettings");
                });

            modelBuilder.Entity("MutinyBot.Models.MemberModel", b =>
                {
                    b.HasOne("MutinyBot.Models.GuildModel", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("MutinyBot.Models.GuildModel", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
