// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MutinyBot.Database;

#nullable disable

namespace MutinyBot.Migrations
{
    [DbContext(typeof(MutinyBotDbContext))]
    [Migration("20230821162538_RemovePets")]
    partial class RemovePets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("MutinyBot.Models.GuildModel", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("JoinLogChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ModerationLogChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrackMemberRoles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrackMessageTimestamps")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("MutinyBot.Models.MemberModel", b =>
                {
                    b.Property<ulong>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CurrentMember")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastMessageTimestampRaw")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleDictionary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesJoined")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesMuted")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemberId", "GuildId");

                    b.HasIndex("GuildId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MutinyBot.Models.UserModel", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MutinyBot.Models.MemberModel", b =>
                {
                    b.HasOne("MutinyBot.Models.GuildModel", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("MutinyBot.Models.GuildModel", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
